- name: "Setup default git configuration"
  git_config:
    name="{{ item.name }}"
    scope=global
    value="{{ item.value }}"
  with_items:
    - { name: "user.name",  value: "{{ git_name }}" }
    - { name: "user.email", value: "{{ git_email }}" }