- name: "Changing PROJECT_ROOT path"
  lineinfile:
    path: "{{ items.project_root }}/ml-backend/settings.py"
    regexp: '^PROJECT_ROOT = '
    insertafter: '^#PROJECT_ROOT = '
    line: 'PROJECT_ROOT = "{{ items.project_root }}/ml-backend"'

- name: "Creating virtualenv"
  pip:
    virtualenv: "{{ items.virtualenv_dir }}"
    virtualenv_python: python3.5
    requirements: "{{ items.project_root }}/ml-backend/requirements.txt"

- name: "Compile PyCrf"
  make:
    chdir: "{{ items.project_root }}/ml-backend/service/ner_analysis_service/pycrf/crf/libcrf/"
    target: all

- name: "Installing Nerf"
  pip:
    name: "{{ items.project_root }}/ml-backend/service/ner_analysis_service/pycrf"
    virtualenv: "{{ items.virtualenv_dir }}"

- name: "Install fastText"
  pip:
    name: "{{ items.project_root }}/ml-backend/service/text_analysis_service/embedding_service/fasttext"
    virtualenv: "{{ items.virtualenv_dir }}"