---
- hosts: server
  remote_user: "{{ user }}"
  become: yes
  become_method: sudo
  vars_files:
      - variables.yml
  roles:
  - java
  - maven
  - postgresql
  - virtualenv-install
  - virtualenv-create
  - idea
  - pycharm
  - spotify

- hosts: server
  remote_user: "{{ user }}"
  vars_files:
      - variables.yml
  roles:
  - system-accounts
#ansible-playbook playbook.yml -v --extra-vars "user=jakub_michalowski12"