- name: "Add PostgreSQL key"
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: "Install pgdg repository (Debian/pgdg)"
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main" update_cache=yes


- name: "Install PostgreSQL 10"
  apt: name={{item}}
  with_items:
    - postgresql
    - postgresql-contrib

- name: "Install PostgreSQL prerequisites."
  apt: name={{ item }} state=latest
  with_items:
    - libpq-dev
    - python-psycopg2
  tags:
    - packages

- name: "Upload pg_hba.conf file"
  copy:
    src: pg_hba.conf
    dest: /etc/postgresql/10/main/pg_hba.conf
    owner: postgres
    group: postgres

- name: "Restart service postgresql.service"
  systemd:
    name: postgresql.service
    state: restarted