jdk_url: http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jdk-10.0.1_linux-x64_bin.tar.gz
jvm_dir: /usr/lib/jvm
jdk_version: jdk-10.0.1
jdk_dir: /usr/lib/jvm/jdk-10.0.1