---
- name: "Set spring backend ip in app-frontend prod"
  lineinfile:
    path: "{{ items.project_root }}/app-frontend/src/environments/environment.prod.ts"
    regexp: '  baseUrl: '
    insertafter: '  baseUrl: '
    line: '  baseUrl: "{{ items.spring_backend_ip }}"'

- name: "Set spring backend ip in app-frontend no-prod"
  lineinfile:
    path: "{{ items.project_root }}/app-frontend/src/environments/environment.ts"
    regexp: '  baseUrl: '
    insertafter: '  baseUrl: '
    line: '  baseUrl: "{{ items.spring_backend_ip }}"'

- name: "Set python backend ip in spring app"
  lineinfile:
    path: "{{ items.project_root }}/src/main/java/com/ramojady/stock_ai/utils/Constants.java"
    regexp: '    String PYTHON_BACKEND_URL = '
    insertafter: '    String PYTHON_BACKEND_URL = '
    line: '    String PYTHON_BACKEND_URL = "{{ items.python_backend_ip }}";'

- name: "Set postgres user from spring point of view"
  lineinfile:
    path: "{{ items.project_root }}/src/main/resources/application.properties"
    regexp: 'spring.datasource.username='
    insertafter: 'spring.datasource.username='
    line: "spring.datasource.username={{ items.postgresql_user }}"

- name: "Set postgres password from spring point of view"
  lineinfile:
    path: "{{ items.project_root }}/src/main/resources/application.properties"
    regexp: 'spring.datasource.password='
    insertafter: 'spring.datasource.password='
    line: "spring.datasource.password={{ items.postgresql_password }}"